name: test
on:
  push:
  pull_request:

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test
